export const apiEndpoints = {
  auth: {
    login: "/api/v2/session/authenticate",
    logout: "/api/v2/session/logout",
    changePassword: "/api/v2/session/change_password",
  },
  tahfidz: {
    surah: "/api/v2/tahfidz/surah",
    ayat: "/api/v2/tahfidz/ayat",
    nilai: "/api/v2/tahfidz/nilai",
    sesiList: "/api/v2/sesi_tahfidz/list",
    listDraft: "/api/v2/tahfidz/list_draft",
    update: "/api/v2/tahfidz/update",
    historySessions: "/api/v2/tahfidz/history/sessions",
    historySiswa: "/api/v2/tahfidz/history/siswa",
    historyDetail: "/api/v2/tahfidz/history/detail",
  },
  guruQuran: {
    halaqohList: "/api/v2/halaqoh/list",
    ustadzList: "/api/v2/ustadz/list",
    absenTahfidzCreate: "/api/v2/absen_tahfidz/create",
    absenTahsinCreate: "/api/v2/absen_tahsin/create",
    absenTahfidzConfirm: "/api/v2/absen_tahfidz/confirm",
  },
  guruAkademik: {
    attendanceDropdown: "/api/v2/guru/absensi/dropdown",
    attendanceStudentsByClass: "/api/v2/guru/absensi/siswa_kelas",
    attendanceList: "/api/v2/guru/absensi/list",
    attendanceDetail: "/api/v2/guru/absensi/detail",
    attendanceCreate: "/api/v2/guru/absensi/create",
    attendanceUpdate: "/api/v2/guru/absensi/update",
    attendanceDone: "/api/v2/guru/absensi/done",
    attendanceDraft: "/api/v2/guru/absensi/draft",
    attendanceDelete: "/api/v2/guru/absensi/delete",
  },
  pelanggaran: {
    list: "/api/v2/pelanggaran/list",
    siswaSearch: "/api/v2/pelanggaran/siswa/search",
    masterJenis: "/api/v2/pelanggaran/master/jenis",
    masterTindakan: "/api/v2/pelanggaran/master/tindakan",
    detail: "/api/v2/pelanggaran/detail",
    create: "/api/v2/pelanggaran/create",
    confirm: "/api/v2/pelanggaran/confirm",
    cancel: "/api/v2/pelanggaran/cancel",
    process: "/api/v2/pelanggaran/process",
    decide: "/api/v2/pelanggaran/decide",
    legacyMaster: "/api/pelanggaran/master",
  },
  kesantrian: {
    managerPerizinanList: "/api/v2/manager/perizinan/list",
    managerPerizinanDetail: "/api/v2/manager/perizinan/detail",
    managerPerizinanDecide: "/api/v2/manager/perizinan/decide",
  },
  musyrif: {
    perizinanList: "/api/v2/musyrif/perizinan/list",
    perizinanDetail: "/api/v2/musyrif/perizinan/detail",
    perizinanCreate: "/api/v2/musyrif/perizinan/create",
    perizinanCheck: "/api/v2/musyrif/perizinan/check",
    siswaList: "/api/v2/musyrif/siswa/list",
    siswaDetail: "/api/v2/musyrif/siswa/detail",
    saldoUangSakuDompet: "/api/v2/musyrif/keuangan/saldo",
    historyUangSakuDompet: "/api/v2/musyrif/keuangan/history",
    topupDompet: "/api/v2/musyrif/keuangan/topup",
    ubahPin: "/api/v2/musyrif/siswa/change_pin",
    tahfidzCreate: "/api/v2/tahfidz_musyrif/create",
    tahfidzList: "/api/v2/tahfidz_musyrif/list",
    pegawaiList: "/api/v2/musyrif/pegawai/list",
  },
  mutabaah: {
    list: "/api/v2/mutabaah/list",
    sesiList: "/api/v2/mutabaah/sesi/list",
    aktivitasList: "/api/v2/mutabaah/aktivitas/list",
    create: "/api/v2/mutabaah/create",
  },
  keamanan: {
    dashboard: "/api/v2/security/dashboard",
    detail: "/api/v2/security/detail",
    checkout: "/api/v2/security/checkout",
    checkin: "/api/v2/security/checkin",
    scanStudent: "/api/v2/security/scan_student",
    searchManual: "/api/v2/security/search_manual",
    updateStatus: "/api/v2/security/update_status",
  },
  legacy: {
    santri: "/api/santri",
    kesehatan: "/api/kesehatan",
    prestasi: "/api/prestasi",
    penilaianMapel: "/api/penilaian-mapel",
    penilaianTahfidz: "/api/penilaian-tahfidz",
    penilaianTahsin: "/api/penilaian-tahsin",
  },
} as const;
