import type { Pelanggaran, Perijinan } from "../domain/kesantrian-types";

const today = new Date().toISOString().slice(0, 10);

export const fallbackPerijinanList: Perijinan[] = [
  {
    id: 9001,
    santriId: 101,
    reference: "KI/26.06/9001",
    tanggalIjin: today,
    tanggalKembali: today,
    keperluan: "Pulang bersama orang tua untuk keperluan keluarga.",
    penjemput: "Ahmad Fauzi",
    jamPenjemputan: "10:00",
    catatan: "Wajib kembali sebelum maghrib.",
    status: "check",
    statusLabel: "Menunggu Persetujuan",
    durasi: "1 Hari",
    namaSantri: "Muhammad Fathir",
    kelasSantri: "IX A",
    kamarSantri: "Kamar Umar",
    halaqohSantri: "Halaqoh 3",
    musyrifName: "Ustadz Rahman",
  },
  {
    id: 9002,
    santriId: 102,
    reference: "KI/26.06/9002",
    tanggalIjin: today,
    tanggalKembali: today,
    keperluan: "Kontrol kesehatan ke klinik bersama wali.",
    penjemput: "Siti Aminah",
    jamPenjemputan: "13:30",
    status: "approve",
    statusLabel: "Disetujui",
    durasi: "1 Hari",
    namaSantri: "Abdullah Naufal",
    kelasSantri: "VIII B",
    kamarSantri: "Kamar Ali",
    halaqohSantri: "Halaqoh 5",
    musyrifName: "Ustadz Hasan",
  },
  {
    id: 9003,
    santriId: 103,
    reference: "KI/26.06/9003",
    tanggalIjin: today,
    tanggalKembali: today,
    keperluan: "Mengikuti acara keluarga bersama wali.",
    penjemput: "H. Burhan",
    jamPenjemputan: "09:15",
    catatan: "Ditolak karena jadwal kegiatan pesantren padat.",
    status: "reject",
    statusLabel: "Ditolak",
    durasi: "1 Hari",
    namaSantri: "Zaidan Alfarizi",
    kelasSantri: "VIII C",
    kamarSantri: "Kamar Abu Bakar",
    halaqohSantri: "Halaqoh 2",
    musyrifName: "Ustadz Yusuf",
    alasanTolak: "Belum bisa izin karena ada agenda wajib pondok.",
  },
  {
    id: 9004,
    santriId: 104,
    reference: "KI/26.06/9004",
    tanggalIjin: today,
    tanggalKembali: today,
    keperluan: "Keperluan administrasi sekolah di luar pesantren.",
    penjemput: "Rudi Hartono",
    jamPenjemputan: "15:00",
    status: "keluar",
    statusLabel: "Sedang Keluar",
    durasi: "1 Hari",
    namaSantri: "Faris Ramadhan",
    kelasSantri: "IX C",
    kamarSantri: "Kamar Utsman",
    halaqohSantri: "Halaqoh 1",
    musyrifName: "Ustadz Ilham",
    waktuKeluar: `${today} 15:05:00`,
  },
];

export const fallbackPelanggaranList: Pelanggaran[] = [
  {
    id: 9101,
    reference: "PL/26.06/9101",
    santriId: 201,
    namaSantri: "Rizky Maulana",
    kelasSantri: "IX B",
    tanggal: today,
    masterPelanggaranId: 12,
    namaPelanggaran: "Terlambat kembali ke asrama",
    jenisPelanggaran: "Kedisiplinan",
    kategori: "Sedang",
    poin: 10,
    tindakan: "Pembinaan",
    deskripsi: "Santri terlambat kembali setelah kegiatan.",
    status: "validasi",
    statusLabel: "Validasi",
    pelaporName: "Musyrif Ahmad",
    infoTindakan: {
      tindakanId: 1,
      tindakanNama: "Pembinaan",
      deskripsiTindakan: "Diberikan pembinaan dan pengingat aturan asrama.",
    },
  },
  {
    id: 9102,
    reference: "PL/26.06/9102",
    santriId: 202,
    namaSantri: "Faiz Hafidz",
    kelasSantri: "VII A",
    tanggal: today,
    masterPelanggaranId: 15,
    namaPelanggaran: "Tidak mengikuti apel",
    jenisPelanggaran: "Kedisiplinan",
    kategori: "Ringan",
    poin: 5,
    deskripsi: "Santri tidak hadir saat apel pagi.",
    status: "proses",
    statusLabel: "Proses",
    pelaporName: "Petugas Kesantrian",
  },
  {
    id: 9103,
    reference: "PL/26.06/9103",
    santriId: 203,
    namaSantri: "Hilmi Akbar",
    kelasSantri: "VIII A",
    tanggal: today,
    masterPelanggaranId: 18,
    namaPelanggaran: "Tidak memakai atribut lengkap",
    jenisPelanggaran: "Kerapian",
    kategori: "Ringan",
    poin: 3,
    deskripsi: "Santri tidak memakai atribut lengkap saat kegiatan.",
    status: "draft",
    statusLabel: "Draft",
    pelaporName: "Petugas Kesantrian",
  },
  {
    id: 9104,
    reference: "PL/26.06/9104",
    santriId: 204,
    namaSantri: "Naufal Ihsan",
    kelasSantri: "IX A",
    tanggal: today,
    masterPelanggaranId: 21,
    namaPelanggaran: "Meninggalkan area tanpa izin",
    jenisPelanggaran: "Keamanan",
    kategori: "Berat",
    poin: 25,
    tindakan: "Pemanggilan wali",
    deskripsi: "Santri meninggalkan area pesantren tanpa izin tertulis.",
    status: "selesai",
    statusLabel: "Selesai",
    pelaporName: "Kepala Bagian Kesantrian",
    infoTindakan: {
      tindakanId: 2,
      tindakanNama: "Pemanggilan wali",
      deskripsiTindakan: "Wali santri dipanggil untuk pembinaan lanjutan.",
    },
    keputusan: {
      userDisetujui: "Manajer Kesantrian",
      catatanKaAsrama: "Selesai dengan pengurangan poin.",
    },
  },
];
