import { useState } from "react";
import { Eye, EyeOff, LockKeyhole } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { authApi } from "@/features/auth/infrastructure/auth-api";

type ChangePasswordDialogProps = { open: boolean; onOpenChange: (open: boolean) => void; onSuccess: () => Promise<void> | void };

export function ChangePasswordDialog({ open, onOpenChange, onSuccess }: ChangePasswordDialogProps) {
  const [oldPassword, setOldPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [error, setError] = useState<string | null>(null); const [pending, setPending] = useState(false); const [visible, setVisible] = useState<Record<string, boolean>>({});
  const close = () => { if (pending) return; setError(null); setOldPassword(""); setNewPassword(""); setConfirmation(""); onOpenChange(false); };
  async function submit() { if (!oldPassword || !newPassword || !confirmation) { setError("Semua field harus diisi."); return; } if (newPassword.length < 6) { setError("Password baru minimal 6 karakter."); return; } if (newPassword !== confirmation) { setError("Konfirmasi password tidak cocok."); return; } setPending(true); setError(null); try { const message = await authApi.changePassword(oldPassword, newPassword); toast.success(message); onOpenChange(false); await onSuccess(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Gagal mengubah password."); } finally { setPending(false); } }
  return <Dialog open={open} onOpenChange={(value) => value ? onOpenChange(true) : close()}><DialogContent showCloseButton={!pending} className="w-[calc(100%-2rem)] max-w-[390px] gap-0 rounded-[22px] p-5"><DialogHeader><DialogTitle className="flex items-center gap-2 text-[17px] font-bold text-slate-900"><LockKeyhole className="size-5 text-[#288DE5]" />Ubah Password</DialogTitle><DialogDescription className="pt-2 text-xs leading-relaxed">Masukkan password lama dan password baru untuk mengubah password Anda.</DialogDescription></DialogHeader><div className="mt-5 space-y-3"><PasswordField label="Password Lama" value={oldPassword} onChange={setOldPassword} visible={visible.old} onToggle={() => setVisible((state) => ({ ...state, old: !state.old }))} /><PasswordField label="Password Baru" value={newPassword} onChange={setNewPassword} visible={visible.new} onToggle={() => setVisible((state) => ({ ...state, new: !state.new }))} hint="Minimal 6 karakter" /><PasswordField label="Konfirmasi Password Baru" value={confirmation} onChange={setConfirmation} visible={visible.confirm} onToggle={() => setVisible((state) => ({ ...state, confirm: !state.confirm }))} />{error ? <p className="rounded-xl bg-red-50 px-3 py-2 text-xs font-medium text-red-600">{error}</p> : null}</div><div className="mt-6 grid grid-cols-2 gap-3"><Button variant="outline" onClick={close} disabled={pending} className="h-11 rounded-xl">Batal</Button><Button onClick={() => void submit()} disabled={pending} className="h-11 rounded-xl bg-[#288DE5]">{pending ? "Menyimpan..." : "Ubah"}</Button></div></DialogContent></Dialog>;
}
function PasswordField({ label, value, onChange, visible, onToggle, hint }: { label: string; value: string; onChange: (value: string) => void; visible?: boolean; onToggle: () => void; hint?: string }) { return <label className="block space-y-1.5"><span className="text-xs font-semibold text-slate-700">{label}</span><div className="relative"><Input type={visible ? "text" : "password"} autoComplete="new-password" value={value} onChange={(event) => onChange(event.target.value)} className="h-11 pr-10" /><button type="button" onClick={onToggle} className="absolute inset-y-0 right-0 px-3 text-slate-400">{visible ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></div>{hint ? <span className="text-[11px] text-[#288DE5]">{hint}</span> : null}</label>; }
