import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { academicClasses, academicStudents, academicSubjects, academicTeachers } from "../../application/guru-akademik-fallback-data";
import { useCreateAcademicAssessment } from "../../application/guru-akademik-queries";
import type { AcademicAssessmentStudentInput } from "../../domain/guru-akademik-types";
import { GuruAkademikHeader } from "../components/guru-akademik-header";

const scoreKeys = ["finalScore", "aspect1", "aspect2", "aspect3", "aspect4", "aspect5", "aspect6"] as const;
type ScoreKey = (typeof scoreKeys)[number];

export function AcademicAssessmentFormPage() {
  const navigate = useNavigate(); const create = useCreateAcademicAssessment();
  const [className, setClassName] = useState(""); const [subjectName, setSubjectName] = useState(""); const [teacherName, setTeacherName] = useState(""); const [schoolYear, setSchoolYear] = useState("2025/2026"); const [semester, setSemester] = useState("Semester 2"); const [kkm, setKkm] = useState("75"); const [scores, setScores] = useState<Record<number, Partial<Record<ScoreKey, string>>>>({});
  const students = useMemo(() => academicStudents.filter((student) => student.className === className), [className]);
  function updateScore(studentId: number, key: ScoreKey, value: string) { if (value && (!/^\d{0,3}$/.test(value) || Number(value) > 100)) return; setScores((current) => ({ ...current, [studentId]: { ...current[studentId], [key]: value } })); }
  function submit() {
    if (!className || !subjectName || !teacherName || !students.length) { toast.error("Kelas, mapel, guru, dan siswa wajib diisi."); return; }
    const items: AcademicAssessmentStudentInput[] = students.map((student) => { const values = scores[student.id] ?? {}; const finalScore = values.finalScore === "" || values.finalScore === undefined ? null : Number(values.finalScore); return { studentId: student.id, studentName: student.name, finalScore, predicate: predicate(finalScore), aspect1: parse(values.aspect1), aspect2: parse(values.aspect2), aspect3: parse(values.aspect3), aspect4: parse(values.aspect4), aspect5: parse(values.aspect5), aspect6: parse(values.aspect6) }; });
    if (items.some((item) => item.finalScore === null)) { toast.error("Nilai akhir seluruh siswa wajib diisi."); return; }
    create.mutate({ id: `nilai-${Date.now()}`, className, subjectName, teacherName, schoolYear, semester, kkm: Number(kkm) || 75, status: "done", items }, { onSuccess: () => { toast.success("Penilaian akhir berhasil disimpan."); navigate("/guru-akademik/penilaian"); }, onError: () => toast.error("Gagal menyimpan penilaian.") });
  }
  return <div className="mx-auto min-h-svh max-w-[430px] bg-[#EFF6FF]"><GuruAkademikHeader title="Penilaian Akhir Guru" subtitle="Input nilai siswa" onBack={() => navigate("/guru-akademik/penilaian")} /><main className="space-y-4 px-4 py-5 pb-24"><Card className="space-y-4 rounded-[22px] border-0 p-4 shadow-sm"><SelectField label="Kelas" value={className} onValueChange={setClassName} placeholder="Pilih kelas" options={academicClasses.map((item) => item.name)} /><SelectField label="Mata Pelajaran" value={subjectName} onValueChange={setSubjectName} placeholder="Pilih mapel" options={academicSubjects.map((item) => item.name)} /><SelectField label="Guru" value={teacherName} onValueChange={setTeacherName} placeholder="Pilih guru" options={academicTeachers.map((item) => item.name)} /><div className="grid grid-cols-2 gap-3"><Field label="Tahun Ajaran"><Input value={schoolYear} onChange={(event) => setSchoolYear(event.target.value)} /></Field><SelectField label="Semester" value={semester} onValueChange={setSemester} placeholder="Semester" options={["Semester 1", "Semester 2"]} /></div><Field label="KKM"><Input type="number" min="0" max="100" value={kkm} onChange={(event) => setKkm(event.target.value)} /></Field></Card><Card className="rounded-[22px] border-0 p-4 shadow-sm"><h2 className="mb-4 text-[15px] font-bold text-slate-900">Nilai Siswa</h2>{students.length ? <div className="space-y-5">{students.map((student) => <StudentScoreRow key={student.id} studentName={student.name} nis={student.nis} score={scores[student.id] ?? {}} onChange={(key, value) => updateScore(student.id, key, value)} />)}</div> : <p className="py-5 text-center text-sm text-slate-400">Pilih kelas untuk memuat siswa.</p>}</Card></main><div className="fixed inset-x-0 bottom-0 z-30 border-t bg-white/95 p-3"><div className="mx-auto max-w-[430px]"><Button onClick={submit} disabled={create.isPending} className="h-12 w-full rounded-2xl bg-[#288DE5] font-bold">Simpan Penilaian</Button></div></div></div>;
}

function StudentScoreRow({ studentName, nis, score, onChange }: { studentName: string; nis: string; score: Partial<Record<ScoreKey, string>>; onChange: (key: ScoreKey, value: string) => void }) { const finalScore = score.finalScore === undefined ? null : Number(score.finalScore); return <div className="border-b border-slate-100 pb-5 last:border-0 last:pb-0"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-semibold text-slate-800">{studentName}</p><p className="text-xs text-slate-400">NIS: {nis}</p></div><span className="rounded-lg bg-violet-50 px-2 py-1 text-xs font-bold text-violet-600">{predicate(finalScore) || "-"}</span></div><div className="mt-3 grid grid-cols-2 gap-2"><ScoreInput label="Nilai Akhir" value={score.finalScore ?? ""} onChange={(value) => onChange("finalScore", value)} />{[1, 2, 3, 4, 5, 6].map((number) => <ScoreInput key={number} label={`Aspek ${number}`} value={score[`aspect${number}` as ScoreKey] ?? ""} onChange={(value) => onChange(`aspect${number}` as ScoreKey, value)} />)}</div></div>; }
function ScoreInput({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="space-y-1"><span className="text-[11px] font-semibold text-slate-500">{label}</span><Input inputMode="numeric" value={value} onChange={(event) => onChange(event.target.value)} placeholder="0-100" className="h-9" /></label>; }
function parse(value?: string) { return value === undefined || value === "" ? null : Number(value); }
function predicate(score: number | null) { if (score === null || Number.isNaN(score)) return ""; if (score >= 90) return "A"; if (score >= 80) return "B"; if (score >= 70) return "C"; return "D"; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1.5"><span className="text-xs font-bold text-slate-500">{label}</span>{children}</label>; }
function SelectField({ label, value, onValueChange, placeholder, options }: { label: string; value: string; onValueChange: (value: string) => void; placeholder: string; options: string[] }) { return <Field label={label}><Select value={value} onValueChange={onValueChange}><SelectTrigger className="h-11 w-full"><SelectValue placeholder={placeholder} /></SelectTrigger><SelectContent>{options.map((option) => <SelectItem key={option} value={option}>{option}</SelectItem>)}</SelectContent></Select></Field>; }
