import { useMemo } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { PageLoadingState } from "@/components/feedback/page-loading-state";
import { GuruAkademikHeader } from "../components/guru-akademik-header";
import { useAcademicAttendance, useDeleteAcademicAttendance, useUpdateAcademicAttendance } from "../../application/guru-akademik-queries";

export function AcademicAttendanceDetailPage() {
  const navigate = useNavigate(); const { attendanceId } = useParams(); const query = useAcademicAttendance(); const update = useUpdateAcademicAttendance(); const remove = useDeleteAcademicAttendance();
  const item = useMemo(() => (query.data ?? []).find((attendance) => String(attendance.id) === attendanceId), [attendanceId, query.data]);
  if (query.isLoading) return <PageLoadingState />;
  if (!item) return <main className="mx-auto min-h-svh max-w-[430px]"><GuruAkademikHeader title="Detail Absensi" onBack={() => navigate("/guru-akademik/absensi")} /><p className="p-6 text-center text-sm text-slate-500">Data absensi tidak ditemukan.</p></main>;
  const count = (status: string) => item.items.filter((student) => student.status === status).length;
  const setState = (state: "draft" | "done") => update.mutate({ ...item, state }, { onSuccess: () => toast.success(state === "done" ? "Absensi berhasil difinalisasi." : "Absensi kembali menjadi draft."), onError: () => toast.error("Gagal memperbarui absensi.") });
  const deleteItem = () => { if (item.state !== "draft") { toast.error("Kembalikan absensi ke draft sebelum menghapus."); return; } if (!window.confirm("Hapus absensi ini?")) return; remove.mutate(item.id, { onSuccess: () => { toast.success("Absensi berhasil dihapus."); navigate("/guru-akademik/absensi", { replace: true }); }, onError: () => toast.error("Gagal menghapus absensi.") }); };
  return <main className="mx-auto min-h-svh max-w-[430px] bg-[#EFF6FF]"><GuruAkademikHeader title="Detail Absensi" subtitle={item.state === "done" ? "Absensi selesai" : "Absensi draft"} onBack={() => navigate("/guru-akademik/absensi")} /><section className="space-y-4 px-4 py-5 pb-28"><Card className="rounded-[22px] border-0 p-4 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-[16px] font-bold">{item.subjectName}</h2><span className={`rounded-lg px-2.5 py-1 text-xs font-bold ${item.state === "done" ? "bg-emerald-50 text-emerald-600" : "bg-slate-100 text-slate-500"}`}>{item.state === "done" ? "Selesai" : "Draft"}</span></div><dl className="mt-4 space-y-2 text-sm"><Row label="Tanggal" value={`${item.day ?? ""}, ${item.date}`} /><Row label="Kelas" value={item.className} /><Row label="Jam Pelajaran" value={`Jam ke-${item.lessonPeriod}`} /><Row label="Guru" value={item.teacherName} /><Row label="Pertemuan" value={`Ke-${item.meetingNumber}`} /></dl></Card><Card className="rounded-[22px] border-0 p-4 shadow-sm"><h2 className="text-[15px] font-bold">Materi</h2><p className="mt-3 text-sm font-semibold">{item.material.content}</p>{item.material.theme ? <p className="mt-1 text-xs text-slate-500">Tema: {item.material.theme}</p> : null}</Card><Card className="rounded-[22px] border-0 p-4 shadow-sm"><h2 className="text-[15px] font-bold">Rekap Kehadiran</h2><p className="mt-3 text-sm text-slate-600">Hadir {count("Hadir")} • Izin {count("Izin")} • Sakit {count("Sakit")} • Alpa {count("Alpa")}</p><div className="mt-4 space-y-3">{item.items.map((student) => <div key={student.id ?? student.studentId} className="flex items-center justify-between border-t border-slate-100 pt-3"><div><p className="text-sm font-semibold">{student.studentName}</p><p className="text-xs text-slate-400">{student.nis ? `NIS: ${student.nis}` : ""}{student.note ? ` • ${student.note}` : ""}</p></div><span className="text-xs font-bold text-slate-600">{student.status}</span></div>)}</div></Card></section><div className="fixed inset-x-0 bottom-0 z-30 border-t bg-white/95 p-3"><div className="mx-auto flex max-w-[430px] gap-2">{item.state === "draft" ? <><Button variant="outline" onClick={deleteItem} disabled={remove.isPending} className="h-11 flex-1 rounded-xl border-red-200 text-red-600">Hapus</Button><Button onClick={() => setState("done")} disabled={update.isPending} className="h-11 flex-[2] rounded-xl bg-[#288DE5]">Finalisasi</Button></> : <Button onClick={() => setState("draft")} disabled={update.isPending} className="h-11 w-full rounded-xl bg-[#288DE5]">Kembalikan ke Draft</Button>}</div></div></main>;
}
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-4"><dt className="text-slate-400">{label}</dt><dd className="text-right font-semibold text-slate-700">{value}</dd></div>; }
